server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Duduxs/ead-config-server-repo
          default-label: main

encrypt:
  key: t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWn

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    instance:
      hostname: ${APP_DOMAIN_NAME}
      non-secure-port: 80